api_login: 
  path: /api/auth/login
  methods: POST

api_register:
  path: /api/auth/register
  methods: POST
  controller: App\Controller\AuthController::register

#videos
free_video:
  path: /api/videos/free
  methods: GET
  controller: App\Controller\VideoController::free

videos:
  path: /api/videos
  methods: GET
  controller: App\Controller\VideoController::index

video:
  path: /api/videos/{id}
  methods: GET
  controller: App\Controller\VideoController::show

create_video:
  path: /api/videos
  methods: POST
  controller: App\Controller\VideoController::store

update_video:
  path: /api/videos/{id}
  methods: PUT
  controller: App\Controller\VideoController::put

delete_video:
  path: /api/videos/{id}
  methods: DELETE
  controller: App\Controller\VideoController::delete



#categories
categories:
  path: /api/categories
  methods: GET
  controller: App\Controller\CategoryController::index

category:
  path: /api/categories/{id}
  methods: GET
  controller: App\Controller\CategoryController::show

videos_per_category:
  path: /api/categories/{id}/videos
  methods: GET
  controller: App\Controller\CategoryController::searchVideosPerCategory

create_category:
  path: /api/categories
  methods: POST
  controller: App\Controller\CategoryController::store

update_category:
  path: /api/categories/{id}
  methods: PUT
  controller: App\Controller\CategoryController::put

delete_category:
  path: /api/categories/{id}
  methods: DELETE
  controller: App\Controller\CategoryController::delete